italia/developers-italia-api

developers-italia.oas.yaml
=> chore(openapi): add TOS link

.env, Dockerfile, docker-compose.yml
Fix docker configuration. DB and API are now working correctly
=> fix(docker): Fix docker configuration

developers-italia.oas.yaml
=> chore(openapi): add Terms of service section

main.go
I think we want this, I don't see any drawbacks in having it (maybe performances while unwinding the stack? :thinking:)
=> feat: don't crash if an handler panics

internal/handlers/status.go, main.go, main_test.go
=> feat: implement /status

developers-italia.oas.yaml
=> chore(openapi): add authentication method

.gitignore, go.mod, go.sum, main_test.go, test/testdata/fixtures/logs.yml
=> test: refactor, add fixtures support and logs tests

developers-italia.oas.yaml, internal/handlers/general/pagination.go, internal/handlers/logs.go, internal/models/models.go, main.go, main_test.go, test/testdata/fixtures/logs.yml
* Add Log testcases
* Sync the OpenAPI spec to the implementation
Fix #14
=> feat: finish the implementation of Logs

.github/workflows/spectral.yaml
=> chore: add checks permissions to spectral action 

developers-italia.oas.yaml, internal/common/errors.go, internal/common/problem_json.go, internal/common/validator.go, internal/handlers/logs.go, internal/handlers/publishers.go, internal/handlers/software.go, main_test.go
The validationError file in problem+json should be an array, not an
array of arrays.
Added the OpenAPI description of the field, added tests.
=> fix: define and fix the type of validationErrors

readme.md
=> Initial WIP of readme.md

.github/workflows/release-chart.yml, charts/developers-italia-api/Chart.yaml
Helm chart versions are "vx.y.z" with corresponding tags "helm/vx.y.z".
=> chore(chart): adopt new tag and version format

internal/common/validator.go, main_test.go
Fix #86 
Updated validator and structure to return proper errors
=> fix(#86): fix validator and update structure

developers-italia.oas.yaml, internal/common/requests.go, internal/handlers/publishers.go, main_test.go
Addiotional Fixes for comments in #12 for Publishers
* Fix docs
* Fix payload for POST publisher
Still remaining:
* Update tests
=> fix(#12): addtional fixes for publishers

internal/common/requests.go, internal/handlers/publishers.go
Fix for publishers model not loading codeHosting relation
Added missing URL Validation
=> fix(publishers): fix for publishers codeHosting preload and validation

developers-italia.oas.yaml, internal/common/constants.go, internal/common/requests.go, internal/database/postgres_database.go, internal/database/sqlite_database.go, internal/handlers/webhooks.go, internal/models/hooks.go, internal/models/models.go, internal/webhooks/webhooks.go, main.go, main_test.go, test/testdata/fixtures/publishers.yml, test/testdata/fixtures/webhooks.yml
=> feat: implement webhooks

developers-italia.oas.yaml, internal/common/validator.go
Remove all warning and info with the Extra security checks profile.
Fix #90.
=> chore(openapi): remove all Spectral warnings

internal/common/requests.go, main_test.go
* ValidationError has a "value" field, not "providedValue"
* Correctly test for Software's PATCH endpoints
* Use the correct argument order for assert.Equal()
=> test: misc fixes

developers-italia.oas.yaml, main.go
=> feat: add response caching and cache-control headers

internal/models/models.go
=> refactor: uniform char casing in GORM tags

main_test.go
Always load all fixtures instead of having to specify the fixtures files for each test, which is tedious and error-prone.
Fix #149.
=> test: always load all fixtures

developers-italia.oas.yaml, internal/common/requests.go, internal/handlers/publishers.go, internal/models/models.go, internal/models/models_test.go, main_test.go, test/testdata/fixtures/publishers.yml
=> feat: rename externalCode to alternativeId

internal/common/requests.go, internal/handlers/publishers.go, main_test.go
=> feat: implement Publishers PATCH

developers-italia.oas.yaml, internal/handlers/publishers.go, main_test.go
=> feat(publishers): make alternativeId work as an id in endpoints

.golangci.yaml
=> fix(ci): disable musttag linter
