.github/workflows/lint.yml
.github/workflows/spectral.yaml
.github/workflows/tests.yml

Filter the branches in workflows so we don't run the same workflow
twice in pull requests.

chore(ci): filter the branches in workflows

---

.github/workflows/lint.yml
.github/workflows/spectral.yaml
.github/workflows/tests.yml

The previous syntax was incorrect, even if GitHub didn't
explicitly complain about it.

chore: fix GitHub Action syntax

---

.goreleaser.yaml

gcr.io is the Google one, I need to sleep more ;)

chore: fix hostname for GitHub container registry

---

main_test.go

This meant to be in https://github.com/italia/developers-italia-api/pull/61, but I didn't include it for some reason :sweat:

test: remove superfluous input data and description from asserts

---

internal/handlers/publishers.go

When the primary key is a string, First() has to be called with an
additional parameter.

fix: use uuidv4 and GORM's syntax for string pk

---

internal/common/requests.go
internal/common/responses.go
internal/handlers/logs.go
internal/handlers/publishers.go
main_test.go

This PR introduces integration tests through GO and Fiber.
A few considerations:
* expectedBody was kept at the end. Implement a tests with strings and JSONs leads a lot of codes and errors due to strict go typing rules.
* In case of a custom validation needed, a "validateFunc" was introduced.

feat(tests): add first support to integration tests

---

.github/workflows/lint.yml

Increase golangci-lint-action timeout because the action takes a
more than 1 minute to run on GitHub's servers (https://github.com/golangci/golangci-lint-action/issues/297).
Enable verbose mode as well, so we can understand what's going on.

chore: increase golangci-lint-action timeout

---

internal/handlers/logs.go

Transactions in gorm need to be explicitly finalized with Commit() or
Rollback(), otherwise they'll keep the connection in use. This is not
really clear in the docs.
Remove the transaction in /logs, as we don't need it anyway.
Fix #109.

fix: remove unused transaction

---

README.md
internal/common/env.go
main.go

The limiter is kinda naive, so let's disable it by default.
When enabled, make it work with proxies (which it's also the scenario
internal our deployment, with the k8s ingress).

feat: make limiter work behind proxy and disable it by default

---

developers-italia.oas.yaml
internal/handlers/general/pagination.go
internal/handlers/logs.go
main_test.go

Have logs endpoints return them ordered from the most recent to the
least recent and document it.
Add correct ordering to Software and Publishers as well by ascending
created_at.

fix: default sorting for resources

---

developers-italia.oas.yaml
go.mod
go.sum
internal/common/requests.go
internal/handlers/software.go
internal/models/models.go
internal/models/models_test.go
main_test.go
test/testdata/fixtures/software.yml
test/testdata/fixtures/software_urls.yml

* Introduce the `url` and `alias` fields instead of a single `urls` field, to better express the concepts.
* Implement PATCH with application/merge-patch+json semantics.
* Don't soft delete Software and SoftwareURLs: because of the unique columns it wouldn't be possible to add a software with a previously used (and deleted) object, because is still there, albeit invisible to the API users.
* Manually handle SoftwareURLs associations, because Update(&software) is not smart enough to synch the associations and remove them when necessary. Replace() with Session(&gorm.Session{FullSaveAssociations: true}) doesn't work either because the foreign key is set to null instead of being deleted and, more importantly, wouldn't even work with our NOT NULL constraint on that foreign key. …

feat!(software): change model and properly implement PATCH

---

internal/models/models.go
internal/models/models_test.go
main_test.go

The email field is used as a way to express a representative for a Publisher, but the same representative can be act as one for different Publishers.

fix: make publisher's email not unique

---

internal/common/requests.go
internal/handlers/publishers.go
internal/models/models.go
internal/models/models_test.go
main_test.go

Publisher's email is just a way to reach a referent person for the publisher, so it's acceptable for different publishers to have the same contact.

fix: make Publisher email optional

---

internal/handlers/publishers.go
main_test.go

Remove `email` from the conflict message as it's no longer a unique field.

fix: publisher conflict message

---

.github/workflows/publish-staging-docker-image.yml
.goreleaser.staging.yaml
Dockerfile

Publish the staging Docker image (ghcr.io/italia/developers-italia-api:main) when pushing to main.

chore(ci): publish the staging Docker image with goreleaser

---

internal/models/models.go

Don't soft delete API resources with unique columns, otherwise it wouldn't be possible to add a previously used (and deleted) resource, because is would still be in the database, albeit invisible to the API users.

fix: don't soft delete resources

---

.github/workflows/publish-staging-docker-image.yml

The last tag can be a non valid semantic version (fe. when we tag with helm/vX.Y.Z), so let's force a valid semantic version for the temporary Goreleaser tag.

chore(ci): always tag for Goreleaser with a valid semantic version

---

internal/common/errors.go
internal/common/validator.go
internal/handlers/logs.go
internal/handlers/software.go
internal/handlers/webhooks.go
main_test.go

Closes issue #166.
This PR adds a "Detail" field to errors generated by the `ErrorWithValidationErrors`. It does so using a new method called `GenerateErrorDetails` which is found in [validator.go](https://github.com/Bavuett/developers-italia-api/blob/778c232b11639be89708c73ca61a469c48a3b5d9/internal/common/validator.go#L76-L98).
Here is an example of how it works: 
**Request.**
**Response.**
Let me know if changes are needed.

Generate "Detail" field for Validation Errors.

---

.golangci.yaml

Re-enable the musttag linter, the issue was fixed upstream.

chore(lint): re-enable musttag linter

---

README.md
internal/database/database.go

Use PostgreSQL as default database, so it works with DSN as well. (fe. host=db user=postgres password=postgres dbname=postgres port=5432)

fix(backward comp): use postgres as default db

---

internal/database/database.go

Workaround for this issue in GORM: https://github.com/go-gorm/gorm/issues/5534

fix: ignore generated column when migrating

---

developers-italia.oas.yaml
internal/handlers/publishers.go
main_test.go

Implementation of `from` and `to` query parameters in `GET /publishers` as asked in #214

Implement from and get in get publishers

---

.github/workflows/publiccode-yml-validation.yml
publiccode.yml

Add publiccode.yml and CI validation for it.
Fix #107.

chore: add publiccode.yml

---

.github/workflows/lint.yml

chore: pin the version of golangci-lint

---

go.mod
go.sum
internal/common/errors.go
main_test.go

**Not actually ready to merge yet**, due to failing tests (see below)
I believe this is right, but I wanted to check that this is looking right to y'all.
Response looks good, identical to response before change, except that the order of properties is moved around.
Because of the changed order in the response, _many_ tests will need to be changed.  For example in TestApi:
``expectedBody:        `{"title":"Not Found","detail":"Cannot GET /v1/i-dont-exist","status":404}`,``
will need to become
``expectedBody:        `{"detail":"Cannot GET /v1/i-dont-exist","status":404,"title":"Not Found"}`,``
and so on.  Lots of little manual changes in the expected body values.  I'll also need to add a check for empty details, because some tests are failing due to `details: ""` being included in the …

gofiber upgrade to v2.51.0 and application/problem+json update

---

go.mod
go.sum
internal/handlers/software.go
internal/models/models.go
main_test.go

SECURITY NOTE:
This doesn't implement any authorization on resources, which is good
*for now* as you either have the ability to write to resources or not
have it.
That MUST be implemented when there will be multiple write tokens with
different scopes.
(See https://github.com/italia/developers-italia-api/issues/188)

feat: implement JSON Patch for Software resource

---

main_test.go

GET /logs test wasn't properly checking for createdAt ordering.

test: fix GET /log test

---

.github/workflows/spectral.yaml

The rules where moved to another repository
(https://github.com/italia/api-oas-checker-rules), get them from there.

chore(ci): fix the Spectral rules URL

---

internal/models/models.go

Remove the associated codeHostings when using DELETE on a publisher.
Code hostings are mapped 1-to-1 with a publisher, so they they're part of the resource.
Not deleting them means we'd have dangling code hosting with no publisher, invisible to the API, and that can't be associated to a publisher anymore.

fix: remove codeHostings when deleting publishers
